name: CI & Publish Pipeline

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Lint, Typecheck, and Tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Run Tests and generate report
        run: npm run test:ci

      - name: Publish Test Report to GitHub UI
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Mocha Tests
          path: report/json/result.json
          reporter: mocha-json

  build:
    runs-on: ubuntu-latest
    name: Build the Project
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build
        run: npm run prepublishOnly

  publish-npm-registry:
    runs-on: ubuntu-latest
    name: Publish to npm
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    environment:
      name: npm-publish
      url: https://www.npmjs.com/package/@mfuon2/chrono-utilz

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          registry-url: 'https://registry.npmjs.org/'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Configure .npmrc for npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Build (Ensure output before publishing)
        run: npm run prepare

      - name: ✅ Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gh-registry:
    runs-on: ubuntu-latest
    name: Publish to GitHub Packages
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          registry-url: 'https://npm.pkg.github.com/'

      - name: Configure .npmrc for GitHub
        run: |
          echo "@mfuon2:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build (Ensure output before publishing)
        run: npm run prepare

      - name: 📦 Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
